name: scinti-clustering
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - numpy
  - pandas
  - scipy
  - scikit-learn
  - matplotlib
  - pytorch
  - pytorch-cuda=12.1
  - pip
  - pip:
      - jupyter
